# 
# ██████╗ ██╗   ██╗███████╗████████╗███████╗███████╗████████╗    ████████╗ ██████╗ ███╗   ███╗██╗     
# ██╔══██╗██║   ██║██╔════╝╚══██╔══╝██╔════╝██╔════╝╚══██╔══╝    ╚══██╔══╝██╔═══██╗████╗ ████║██║     
# ██████╔╝██║   ██║███████╗   ██║   █████╗  ███████╗   ██║          ██║   ██║   ██║██╔████╔██║██║     
# ██╔═══╝ ██║   ██║╚════██║   ██║   ██╔══╝  ╚════██║   ██║          ██║   ██║   ██║██║╚██╔╝██║██║     
# ██║     ╚██████╔╝███████║   ██║   ███████╗███████║   ██║          ██║   ╚██████╔╝██║ ╚═╝ ██║███████╗
# ╚═╝      ╚═════╝ ╚══════╝   ╚═╝   ╚══════╝╚══════╝   ╚═╝          ╚═╝    ╚═════╝ ╚═╝     ╚═╝╚══════╝
#                                                     rustfmt.toml

max_width = 100
use_small_heuristics = "Max"
wrap_comments = true
edition = "2021"
newline_style = "Unix"
reorder_imports = true
